pipeline {
    agent { 
        node { 
            label 'jenkins_slave'
        }
    }
    environment {
        AZ_DOCKER_KEY_ID     = 'jenkins-user-for-docker-repository'
        REPOSITORY           = 'hansleolml/reto_tecnico'
        REPOSITORY_BD        = 'hansleolml/reto_tecnico_bd'
        AZ_K8S_KEY_ID        = 'jenkins-user-for-k8s-azure'
    }
    stages {
        stage('Git Clone'){
            steps {
                git credentialsId: 'jenkins-user-for-git-repository', url: 'https://github.com/hansleolml/retobase_prueba.git'
            }
        }
        stage('Docker Build') {
            steps {
                script{
                    //customImage = docker.build(REPOSITORY_BD+":${env.BUILD_ID}/")
                    sh 'docker build -t ${env.REPOSITORY_BD}:latest /mysql'
                }
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}
